name: FUDGE Automatic npm audit fix

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install

      - name: Audit fix
        run: npm audit fix
